[files]
extend-exclude = [
    "crates/syntax/test_data",
]

[default.extend-words]
typ = "typ" # Uncollide keyword `type`.
froms = "froms"
regist = "regist" # coc.nvim `registLanguageClient`
withs = "withs"
